### ISSUE TITLE
Javascript Error - Index (Fresh Install)

### ISSUE THREAD

**Issue by JigSawFr** [Jatax/TKS#7]
When you make a fresh install of the latest version,
You have an error when you go to index page.
A javascript error appear with this text:

"DataTables warning: table id=9cafffae02d28634e53ec9e2967d72a2 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

**Comment by JigSawFr** [comment]
Tested with Firefox 35.0 on Windows 10

**Comment by JigSawFr** [comment]
Solved - OVH hosting.
At OVH, Strict errors are shown. So JSON response to index array is invalide due of stricts errors.
To fix it:
Open api.php / script.php & rss.php

Comment line:
ini_set('display_errors', 1);

Or set it to "0" or "off"

Enjoy. :8ball:

**Comment by Jatax** [comment]
In next version, debugmod argument in config fil will turn on or off this option.
