### ISSUE TITLE
RSS not deleted after tracker removed !

### ISSUE THREAD

**Issue by JigSawFr** [Jatax/TKS#8]
There is a bug when you delete a tracker,
The rss is not delete in the same time,
But the title in RSS is deleted.
So you can't remove RSS, an error appear.
"Tracker Title is empty"
![genisys_-_2015-01-23_11 03 51](https://cloud.githubusercontent.com/assets/5781907/5872778/a19155ae-a2ef-11e4-97e5-9fa8b3220752.png)

**Comment by Jatax** [comment]
It will be corrected ...
A solution is to clean DB with "Purger BDD".

**Comment by JigSawFr** [comment]
Thanks, fixed with this :+1:
