### ISSUE TITLE
Confirm before purge database

### ISSUE THREAD

**Issue by JigSawFr** [Jatax/TKS#9]
I think purge is a important function because, all database entries are deleted...but without confirmation.
In fact, you can erase all data without thinking to that or by making a mistake action.
So, it could be a good idea to ask user to confirm this action and to explain what it will happend !
Thanks you :)

**Comment by Jatax** [comment]
Indeed ...
But it does not remove all data ... just datas with error (rss without tracker, torrent without tracker, release without torrents ...).
You could find a dump of your database before purge in "saves".
